# Generated by Django 5.2.8 on 2025-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Gelir'), ('EXPENSE', 'Gider')], default='EXPENSE', max_length=7),
        ),
    ]
